#version 460 core

#define MAX_FLOAT intBitsToFloat(2139095039)


layout (std140, binding = 0) readonly buffer in_WorldMap {
	uint in_branchs[];
};

layout (std140, binding = 1) readonly buffer in_Camera {
	vec3 in_cameraPosition;
	float in_fov;
	vec2 in_cameraOrientation;
	ivec2 in_screenSize;
};

layout (std140, binding = 2) buffer out_WorldMap {
	vec3 out_hittedBlocks[];
};


layout (local_size_x = 256, local_size_y = 256, local_size_z = 1) in;


void main() {
	ivec2 halfScreenSize = in_screenSize / 2;
	uvec2 currentPixel = gl_GlobalInvocationID.xy;
	float verticalFov = 2 * atan(halfScreenSize.y);

	uint out_index = currentPixel.y * in_screenSize.x + currentPixel.x;

	vec2 relativeCurrentPixel = (vec2(currentPixel.xy) - halfScreenSize) / halfScreenSize;
	vec2 currentRelativeAngles = vec2(
		atan(relativeCurrentPixel.x * tan(1)) * in_fov,
		atan(relativeCurrentPixel.y * tan(1)) * verticalFov
	);

	out_hittedBlocks[out_index] = vec3(relativeCurrentPixel.xy, 0.0);
}
