#version 460 core

#define VERTEX_COUNT 14


layout (std140, binding = 0) readonly buffer in_WorldMap {
	uint in_branchs[];
};

layout (std140, binding = 1) readonly buffer in_Camera {
	ivec2 in_screenSize;
	float in_cameraNearDistance;
	float in_fov;
	vec3 in_cameraPosition;
	vec3 in_cameraOrientation;
};

layout (std140, binding = 2) buffer out_WorldMap {
	uint out_hittedBlocks[];
};


void main() {
	float width = 2*in_cameraNearDistance*tan(in_fov/2);
	float cameraPixelSize = float(in_screenSize.x) / width;
	ivec2 currentPixel = ivec2(gl_GlobalInvocationID.xy);
}